---
systemProperties:
  jenkins.install.runSetupWizard: "true"
  jenkins.model.Jenkins.slaveAgentPort: "5000"
  jenkins.model.Jenkins.slaveAgentPortEnforce: "true"
plugins:
- groupId: "org.jenkins-ci.plugins"
  artifactId: "dotnet-as-script"
  source:
    version: "1.0.2"
- groupId: "org.jenkins-ci.plugins"
  artifactId: "ApicaLoadtest"
  source:
    version: "1.10"
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.107.3"
buildSettings:
  docker:
    build: "true"
    tag: "jenkins-experimental/custom-war-packager-casc-demo"
    base: "jenkins/jenkins:2.138.2"
bundle:
  vendor: "Jenkins project"
  groupId: "io.jenkins.tools.custom-distribution-service.build"
  description: "New Jenkins Version"
  artifactId: "jenkins-all-latest"
  title: "Jenkins WAR - all latest"
